name: whisk
description: "Multi-environment authoring workspace for documents, diagrams and technical writing."
publish_to: 'none'

version: 0.16.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  pdfrx: ^2.4.1
  path_provider: ^2.1.5
  file_picker: ^11.0.2
  http: ^1.6.0
  archive: ^4.0.9
  watcher: ^1.2.1
  yaml: ^3.1.2
  pubspec_yaml: ^3.1.0
  url_launcher: ^6.2.5
  rust_lib_whisk:
    path: rust_builder
  flutter_rust_bridge: 2.12.0
  flutter_markdown: ^0.7.6
  flutter_smooth_markdown: ^0.7.4
  flutter_math_fork: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  cider: ^0.2.10

flutter:
  uses-material-design: true

  assets:
    - assets/whisk_icon.png
