// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/collaboration.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1920715800;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_whisk',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiCollaborationCollaborationEngineApplyLocalEdit({
    required CollaborationEngine that,
    required String filePath,
    required RustTextOperation op,
  });

  bool crateApiCollaborationCollaborationEngineApplyRemoteUpdate({
    required CollaborationEngine that,
    required String filePath,
    required List<int> update,
  });

  Uint8List crateApiCollaborationCollaborationEngineEncodeFullUpdate({
    required CollaborationEngine that,
    required String filePath,
  });

  Uint8List crateApiCollaborationCollaborationEngineEncodeStateVector({
    required CollaborationEngine that,
    required String filePath,
  });

  Uint8List crateApiCollaborationCollaborationEngineEncodeUpdateSince({
    required CollaborationEngine that,
    required String filePath,
    required List<int> stateVector,
  });

  String crateApiCollaborationCollaborationEngineGetText({
    required CollaborationEngine that,
    required String filePath,
  });

  void crateApiCollaborationCollaborationEngineLoadFileSnapshot({
    required CollaborationEngine that,
    required String filePath,
    required String text,
  });

  CollaborationEngine crateApiCollaborationCollaborationEngineNew();

  Future<void> crateApiCollaborationCollaborationEngineStartSession({
    required CollaborationEngine that,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CollaborationEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CollaborationEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CollaborationEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiCollaborationCollaborationEngineApplyLocalEdit({
    required CollaborationEngine that,
    required String filePath,
    required RustTextOperation op,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_box_autoadd_rust_text_operation(op, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiCollaborationCollaborationEngineApplyLocalEditConstMeta,
        argValues: [that, filePath, op],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCollaborationCollaborationEngineApplyLocalEditConstMeta =>
      const TaskConstMeta(
        debugName: "CollaborationEngine_apply_local_edit",
        argNames: ["that", "filePath", "op"],
      );

  @override
  bool crateApiCollaborationCollaborationEngineApplyRemoteUpdate({
    required CollaborationEngine that,
    required String filePath,
    required List<int> update,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_list_prim_u_8_loose(update, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiCollaborationCollaborationEngineApplyRemoteUpdateConstMeta,
        argValues: [that, filePath, update],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCollaborationCollaborationEngineApplyRemoteUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "CollaborationEngine_apply_remote_update",
        argNames: ["that", "filePath", "update"],
      );

  @override
  Uint8List crateApiCollaborationCollaborationEngineEncodeFullUpdate({
    required CollaborationEngine that,
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiCollaborationCollaborationEngineEncodeFullUpdateConstMeta,
        argValues: [that, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCollaborationCollaborationEngineEncodeFullUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "CollaborationEngine_encode_full_update",
        argNames: ["that", "filePath"],
      );

  @override
  Uint8List crateApiCollaborationCollaborationEngineEncodeStateVector({
    required CollaborationEngine that,
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiCollaborationCollaborationEngineEncodeStateVectorConstMeta,
        argValues: [that, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCollaborationCollaborationEngineEncodeStateVectorConstMeta =>
      const TaskConstMeta(
        debugName: "CollaborationEngine_encode_state_vector",
        argNames: ["that", "filePath"],
      );

  @override
  Uint8List crateApiCollaborationCollaborationEngineEncodeUpdateSince({
    required CollaborationEngine that,
    required String filePath,
    required List<int> stateVector,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_list_prim_u_8_loose(stateVector, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiCollaborationCollaborationEngineEncodeUpdateSinceConstMeta,
        argValues: [that, filePath, stateVector],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCollaborationCollaborationEngineEncodeUpdateSinceConstMeta =>
      const TaskConstMeta(
        debugName: "CollaborationEngine_encode_update_since",
        argNames: ["that", "filePath", "stateVector"],
      );

  @override
  String crateApiCollaborationCollaborationEngineGetText({
    required CollaborationEngine that,
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCollaborationCollaborationEngineGetTextConstMeta,
        argValues: [that, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCollaborationCollaborationEngineGetTextConstMeta =>
      const TaskConstMeta(
        debugName: "CollaborationEngine_get_text",
        argNames: ["that", "filePath"],
      );

  @override
  void crateApiCollaborationCollaborationEngineLoadFileSnapshot({
    required CollaborationEngine that,
    required String filePath,
    required String text,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiCollaborationCollaborationEngineLoadFileSnapshotConstMeta,
        argValues: [that, filePath, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCollaborationCollaborationEngineLoadFileSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "CollaborationEngine_load_file_snapshot",
        argNames: ["that", "filePath", "text"],
      );

  @override
  CollaborationEngine crateApiCollaborationCollaborationEngineNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCollaborationCollaborationEngineNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCollaborationCollaborationEngineNewConstMeta =>
      const TaskConstMeta(debugName: "CollaborationEngine_new", argNames: []);

  @override
  Future<void> crateApiCollaborationCollaborationEngineStartSession({
    required CollaborationEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiCollaborationCollaborationEngineStartSessionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCollaborationCollaborationEngineStartSessionConstMeta =>
      const TaskConstMeta(
        debugName: "CollaborationEngine_start_session",
        argNames: ["that"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CollaborationEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CollaborationEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine;

  @protected
  CollaborationEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CollaborationEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CollaborationEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CollaborationEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CollaborationEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CollaborationEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  RustTextOperation dco_decode_box_autoadd_rust_text_operation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_text_operation(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  RustTextOperation dco_decode_rust_text_operation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustTextOperation(
      offset: dco_decode_u_32(arr[0]),
      insertedText: dco_decode_String(arr[1]),
      deletedLength: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CollaborationEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CollaborationEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CollaborationEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CollaborationEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CollaborationEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CollaborationEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  RustTextOperation sse_decode_box_autoadd_rust_text_operation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_text_operation(deserializer));
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  RustTextOperation sse_decode_rust_text_operation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offset = sse_decode_u_32(deserializer);
    var var_insertedText = sse_decode_String(deserializer);
    var var_deletedLength = sse_decode_u_32(deserializer);
    return RustTextOperation(
      offset: var_offset,
      insertedText: var_insertedText,
      deletedLength: var_deletedLength,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    CollaborationEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CollaborationEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    CollaborationEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CollaborationEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCollaborationEngine(
    CollaborationEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CollaborationEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_rust_text_operation(
    RustTextOperation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_text_operation(self, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_rust_text_operation(
    RustTextOperation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.offset, serializer);
    sse_encode_String(self.insertedText, serializer);
    sse_encode_u_32(self.deletedLength, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class CollaborationEngineImpl extends RustOpaque
    implements CollaborationEngine {
  // Not to be used by end users
  CollaborationEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CollaborationEngineImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_CollaborationEngine,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CollaborationEngine,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CollaborationEnginePtr,
  );

  void applyLocalEdit({
    required String filePath,
    required RustTextOperation op,
  }) => RustLib.instance.api
      .crateApiCollaborationCollaborationEngineApplyLocalEdit(
        that: this,
        filePath: filePath,
        op: op,
      );

  bool applyRemoteUpdate({
    required String filePath,
    required List<int> update,
  }) => RustLib.instance.api
      .crateApiCollaborationCollaborationEngineApplyRemoteUpdate(
        that: this,
        filePath: filePath,
        update: update,
      );

  Uint8List encodeFullUpdate({required String filePath}) => RustLib.instance.api
      .crateApiCollaborationCollaborationEngineEncodeFullUpdate(
        that: this,
        filePath: filePath,
      );

  Uint8List encodeStateVector({required String filePath}) => RustLib
      .instance
      .api
      .crateApiCollaborationCollaborationEngineEncodeStateVector(
        that: this,
        filePath: filePath,
      );

  Uint8List encodeUpdateSince({
    required String filePath,
    required List<int> stateVector,
  }) => RustLib.instance.api
      .crateApiCollaborationCollaborationEngineEncodeUpdateSince(
        that: this,
        filePath: filePath,
        stateVector: stateVector,
      );

  String getText({required String filePath}) =>
      RustLib.instance.api.crateApiCollaborationCollaborationEngineGetText(
        that: this,
        filePath: filePath,
      );

  void loadFileSnapshot({required String filePath, required String text}) =>
      RustLib.instance.api
          .crateApiCollaborationCollaborationEngineLoadFileSnapshot(
            that: this,
            filePath: filePath,
            text: text,
          );

  Future<void> startSession() => RustLib.instance.api
      .crateApiCollaborationCollaborationEngineStartSession(that: this);
}
