// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CollaborationFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CollaborationEngine>>
abstract class CollaborationEngine implements RustOpaqueInterface {
  void applyLocalEdit({
    required String filePath,
    required RustTextOperation op,
  });

  String getText({required String filePath});

  void loadFileSnapshot({required String filePath, required String text});

  factory CollaborationEngine() =>
      RustLib.instance.api.crateApiCollaborationCollaborationEngineNew();

  Future<void> startSession();
}

class RustTextOperation {
  final int offset;
  final String insertedText;
  final int deletedLength;

  const RustTextOperation({
    required this.offset,
    required this.insertedText,
    required this.deletedLength,
  });

  @override
  int get hashCode =>
      offset.hashCode ^ insertedText.hashCode ^ deletedLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustTextOperation &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          insertedText == other.insertedText &&
          deletedLength == other.deletedLength;
}
